
CREATE TABLE IF NOT EXISTS favourites (
	user_id INTEGER NOT NULL,
	product_id INTEGER NOT NULL,
	like_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP,
	PRIMARY KEY (user_id, product_id, like_date)
);

