steps:
  # Build service-discovery
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'service-discovery', '-am', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/service-discovery:0.1.0', '-f', 'service-discovery/Dockerfile', '.']
  
  # Build cloud-config
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'cloud-config', '-am', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloud-config:0.1.0', '-f', 'cloud-config/Dockerfile', '.']
  
  # Build user-service
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'user-service', '-am', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/user-service:0.1.0', '-f', 'user-service/Dockerfile', '.']

  # Build proxy-client
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'proxy-client', '-am', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/proxy-client:0.1.0', '-f', 'proxy-client/Dockerfile', '.']

  # Build api-gateway
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'api-gateway', '-am', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/api-gateway:0.1.0', '-f', 'api-gateway/Dockerfile', '.']

  # Build product-service
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'product-service', '-am', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/product-service:0.1.0', '-f', 'product-service/Dockerfile', '.']

  # Build order-service
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'order-service', '-am', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/order-service:0.1.0', '-f', 'order-service/Dockerfile', '.']

  # Build payment-service
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'payment-service', '-am', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/payment-service:0.1.0', '-f', 'payment-service/Dockerfile', '.']

  # Build shipping-service
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'shipping-service', '-am', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/shipping-service:0.1.0', '-f', 'shipping-service/Dockerfile', '.']

  # Build favourite-service
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package', '-pl', 'favourite-service', '-am', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/favourite-service:0.1.0', '-f', 'favourite-service/Dockerfile', '.']

images:
  - 'gcr.io/$PROJECT_ID/service-discovery:0.1.0'
  - 'gcr.io/$PROJECT_ID/cloud-config:0.1.0'
  - 'gcr.io/$PROJECT_ID/user-service:0.1.0'
  - 'gcr.io/$PROJECT_ID/proxy-client:0.1.0'
  - 'gcr.io/$PROJECT_ID/api-gateway:0.1.0'
  - 'gcr.io/$PROJECT_ID/product-service:0.1.0'
  - 'gcr.io/$PROJECT_ID/order-service:0.1.0'
  - 'gcr.io/$PROJECT_ID/payment-service:0.1.0'
  - 'gcr.io/$PROJECT_ID/shipping-service:0.1.0'
  - 'gcr.io/$PROJECT_ID/favourite-service:0.1.0'

timeout: 3600s
options:
  machineType: 'E2_HIGHCPU_8'