
CREATE TABLE IF NOT EXISTS orders (
	order_id SERIAL PRIMARY KEY,
	cart_id INTEGER,
	order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	order_desc VARCHAR(255),
	order_fee DECIMAL(7, 2),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	updated_at TIMESTAMP
);

